### ISSUE TITLE
Compressing long author lists

### ISSUE THREAD

**Issue by ebjohnsen** [mgttlinger/biblatex-lncs#4]
Hi,

if I add the option maxnames=2 to biber, I would expect the names of coauthors to be replaced by "et al.", however this doesn't happen and instead the list of authors is simply truncated (no "et al."). (You can try with eg ref 4 in the example file.) Any suggestion how to fix this? 

BW,
Einar

**Comment by mgttlinger** [comment]
Thank you for raising this issue. I currently have an important deadline in a few days but I will look into it next week.

**Comment by ebjohnsen** [comment]
As a quick fix, I replaced line 138 in lncs.bbx by
   {\ifmorenames{\addcomma\space\etal:}}%
but there are probably better (or more standard) solutions.

Einar

**Comment by mgttlinger** [comment]
I pushed the fix to CTAN so hopefully, it will be available soon. Thanks again for raising the issue.
