### ISSUE TITLE
Setting maxbibnames lets crash

### ISSUE THREAD

**Issue by donludovico** [mgttlinger/biblatex-lncs#5]
Hi,

when setting the option `maxbibnames`,  which biblatex-lncs sets to 99, to small values (e.g. 3), I do get an "undefined control sequence" error message.

Way to reproduce:
1. Take biblatex-lncs-test.tex from repository
2. add biblatex option `maxbibnames=3, `
3. compile

Error Message: Undefined Control sequence 
 \addcomma \nbspace 
                              \bibstring [\emph ]{andothers}:
-> i.e. `\nbspace` is not known.

This error refers to 'lncs.bbx' (master) at line 138
`{\ifmorenames{\addcomma\nbspace\bibstring[\emph]{andothers}:}}%`

Unfortunately,I have no clue why. However, Google has almost no search results on "\nbspace". Could one use `~` (as non-breaking space - my guess) instead?

I think this should also turn up, if `maxnames` is set as this internally sets `maxbibnames`, which influences `\ifmorenames`.

Regards
Stephan

**Comment by mgttlinger** [comment]
Thanks for reporting this bug. Coincidentally, I hit exactly that bug a few days ago but forgot to push the bugfix. You are right, the `nbspace` macro was an issue. Another issue is that one of the `ifmorenames` calls was missing an else branch. Both are fixed now. I will submit to CTAN soon.

**Comment by donludovico** [comment]
Thank you for that quick response!
